routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
	'devices' => 'DeviceController',
]);

Route::get('devices/{deviceAuth}/temperature', 'TemperatureMeasureController@index')->name('temperature.index')->middleware('auth');
Route::get('devices/{deviceAuth}/battery', 'BatteryMeasureController@show')->name('battery.show')->middleware('auth');

Route::get('/profile', 'UserAvatarController@edit')->name('profile');
Route::post('profile', 'UserAvatarController@update');

resources/views/partials/footer.blade.php
<footer>
	<!-- common scripts -->
	<script src="{{ asset('js/app.js')}}"></script>
	<script type="text/javascript">
		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			}
		});
	</script>
	<!-- page specific scripts -->
	@yield('pagespecificscripts')
</footer>
</html>

resources/views/partials/header.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Sensiit</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,600" rel="stylesheet" type="text/css">
    <!-- Bootstrap core CSS -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/menu.css') }}" rel="stylesheet">
    @yield('css')

    <!-- Styles -->
    <style>
    html, body {
        background-color: #fff;
        color: #636b6f;
        font-family: 'Nunito', sans-serif;
        font-weight: 200;
        height: 100vh;
        margin: 0;
    }

    .full-height {
        height: 100vh;
    }

    .flex-center {
        align-items: center;
        display: flex;
        justify-content: center;
    }

    .position-ref {
        position: relative;
    }

    .top-right {
        position: absolute;
        right: 10px;
        top: 18px;
    }

    .links > a {
        color: #636b6f;
        padding: 0 25px;
        font-size: 13px;
        font-weight: 600;
        letter-spacing: .1rem;
        text-decoration: none;
        text-transform: uppercase;
    }

</style>
</head>

resources/views/partials/navigation.blade.php
<nav class="navbar navbar-expand-md navbar-dark navbar-laravel">
	<div class="container">
		<a class="navbar-brand" href="{{ url('/welcome') }}">
			{{ config('app.name', 'Laravel') }}
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<!-- Left Side Of Navbar -->
			<ul class="navbar-nav mr-auto">
				@auth
				<li class="nav-item {{ Request::is('ads*') ? 'active' : '' }}">
					<a class="nav-link" href="{{ route('devices.index') }}">{{ __('Mes devices') }}</a>
				</li>
				@endauth
			</ul>

			<!-- Right Side Of Navbar -->
			<ul class="navbar-nav ml-auto">
				<!-- Authentication Links -->
				@guest
				<li class="nav-item">
					<a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
				</li>
				<li class="nav-item">
					@if (Route::has('register'))
					<a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
					@endif
				</li>
				@else
				<li class="nav-item">
					<img src="{{ asset('storage/app/' . Auth::user()->avatar) }}" style="width:50px; height:50px; float:left; border-radius:50%; margin-right:25px;">
				</li>
				<li class="nav-item dropdown">
					<a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
						{{ Auth::user()->name }} <span class="caret"></span>
					</a>
					{{-- <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{{ route('profile') }}"
						onclick="event.preventDefault();
						document.getElementById('change-user-avatar').submit();">
						{{ __('Changer mon image') }}
					</a> --}}
					<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="{{ route('profile') }}"
						onclick="event.preventDefault();
						document.getElementById('change-user-avatar').submit();">
						{{ __('Changer mon image') }}
					</a>
					<a class="dropdown-item" href="{{ route('logout') }}"
					onclick="event.preventDefault();
					document.getElementById('logout-form').submit();">
					{{ __('Logout') }}
				</a>

				<form id="change-user-avatar" action="{{ route('profile') }}" method="GET" style="display: none;">
					@csrf
				</form>
				<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
					@csrf
				</form>
			</div>
		</li>
		@endguest
	</ul>
</div>
</div>
</nav>