routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resources([
	'devices' => 'DeviceController',
]);

Route::get('devices/{deviceAuth}/temperature', 'TemperatureMeasureController@index')->name('temperature.index')->middleware('auth');
Route::get('devices/{deviceAuth}/battery', 'BatteryMeasureController@show')->name('battery.show')->middleware('auth');

Route::get('/profile', 'UserAvatarController@edit')->name('profile');
Route::post('profile', 'UserAvatarController@update');

app/Device.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Iatstuti\Database\Support\CascadeSoftDeletes;

class Device extends Model
{
    use SoftDeletes, CascadeSoftDeletes;

    /**
    * The child model instances that should be softdeleted.
    *
    * @var array
    */

    protected $cascadeDeletes = ['temperatureMeasures', 'batteryMeasures'];

    /**
    * The attributes that should be mutated to dates.
    *
    * @var array
    */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['*'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    public function user(){
        return $this->belongsTo('App\User');
    }

    public function temperatureMeasures(){
        return $this->hasMany('App\Temperature_measure');
    }

    public function batteryMeasures(){
        return $this->hasMany('App\Battery_measure');
    }
}

app/Http/Controllers/DeviceController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Device;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\DeviceRequest;

class DeviceController extends Controller
{

    public function __construct()
    {
        //Oblige l'utilisateur à être authentifié pour accéder au formulaire
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        //Check authorization
        $this->authorize('view', Device::class);

        //Get the current user
        $user = \Auth::user();

        //Get the devices of the user
        $devices = $user->devices()->paginate(5);

        // load the view and pass devices
        return view('device.index', compact('devices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Check authorization
        $this->authorize('create', Device::class);

        return view('device.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(DeviceRequest $request)
    {
        //Check authorization
        $this->authorize('create', Device::class);

        //Form validator
        $validated = $request->validated();

        //Create the device instance
        $device = new device;

        //Fields management
        $device->auth = substr(base_convert(sha1(uniqid(mt_rand())), 16, 36), 0, 40);
        $device->name = $request->name;
        $device->sigfox_id = $request->sigfox_id;
        $device->remote_id = '';
        $device->remote_name = '';

        //Relationships management
        $device->user()->associate(Auth::id());

        //Save the device instance
        $device->save();

        //Flash message
        flash('Device créé!!')->success();

        return redirect('devices/' . $device->auth);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Device  $device
     * @return \Illuminate\Http\Response
     */
    public function show(String $auth)
    {

        //Get the device
        $device = Device::where('auth', $auth)->firstOrFail();

        //Check authorization
        $this->authorize('view', $device);

        return view('device.show', compact('device'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Device  $device
     * @return \Illuminate\Http\Response
     */
    public function edit(String $auth)
    {
        //Get the device
        $device = Device::where('auth', $auth)->firstOrFail();

        //Check authorization
        $this->authorize('update', $device);

        return view('device.edit', compact('device'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Device  $device
     * @return \Illuminate\Http\Response
     */
    public function update(DeviceRequest $request, String $auth)
    {
        //Get the device
        $device = Device::where('auth', $auth)->firstOrFail();

        //Check authorization
        $this->authorize('update', $device);

        //Form validator
        $validated = $request->validated();

        //Fields management
        $device->auth = $auth;
        $device->name = $request->name;
        $device->sigfox_id = $request->sigfox_id;
        $device->remote_id = '';
        $device->remote_name = '';

        //Relationships management
        $device->user()->associate(Auth::id());

        //Save the device instance
        $device->save();

        //Flash message
        flash('Device créé!!')->success();

        return redirect('devices/' . $device->auth);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Device  $device
     * @return \Illuminate\Http\Response
     */
    public function destroy(String $auth)
    {
        //Get the device
        $device = Device::where('auth', $auth)->firstOrFail();

        //Check authorization
        $this->authorize('delete', $device);

        //Delete the device
        $device->delete();

        return redirect('devices')->with('success','Le device a été supprimé');
    }
}

resources/views/device/create.blade.php
@extends('layouts.main')

@section('css')
@endsection
@section('content')

<!-- Gestion des erreurs -->
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div><br />
@endif

{!! Form::open(['url' => route('devices.store'), 'method' => 'POST', 'enctype' => 'multipart/form-data', 'files' => true]) !!}
{!!  Form::token() !!}

<div class="form-group" >

    {!! Form::label('name', 'Nom de votre device') !!}
    {!! Form::input('text', 'name', null, ['class' => 'form-control']) !!}

    {!! Form::label('sigfox_id', 'ID Sigfox'); !!}
    {!! Form::input('text', 'sigfox_id', null, ['class' => 'form-control']) !!}

    {!! Form::submit('Ajouter mon device', ['class' => 'btn btn-primary float-right mt-3']) !!}

</div>

{!! Form::close() !!}

@endsection
@section('pagespecificscripts')
@stop

resources/views/device/edit.blade.php
@extends('layouts.main')

@section('css')
@endsection
@section('content')

<!-- Gestion des erreurs -->
@if ($errors->any())
<div class="alert alert-danger">
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div><br />
@endif

{{-- Form --}}
{!! Form::open(['url' => route('devices.update', $device->auth), 'method' => 'PUT']) !!}
{!!  Form::token() !!}

<div class="form-group" >

    {!! Form::label('name', 'Nom de votre device') !!}
    {!! Form::input('text', 'name', $device->name ? : null, ['class' => 'form-control']) !!}

    {!! Form::label('sigfox_id', 'ID Sigfox'); !!}
    {!! Form::input('text', 'sigfox_id', $device->sigfox_id ? : null, ['class' => 'form-control']) !!}

    {!! Form::submit('Modifier mon device', ['class' => 'btn btn-primary float-right mt-3']) !!}

</div>

{!! Form::close() !!}

@endsection
@section('pagespecificscripts')
@stop

resources/views/device/index.blade.php
@extends('layouts.main')

@section('content')
<div style="display: flex;">
	<div>
		<h1>Mes devices</h1>
	</div>
	<div style="margin: 5px 0 0 40px; width: 150px;">
		<form action="{{ url('/devices/create') }}">
			{{method_field('GET')}}
			{!! csrf_field() !!}
			<button class="btn btn-small btn-secondary mb-1 col-12" type="submit">Créer un nouveau device</button>
		</form>
	</div>
</div>
@include('flash::message')
<div class="jumbotron text-center">
	<h2></h2>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Nom</th>
				<th>ID Sigfox</th>
				<th>ID distant</th>
				<th>Nom distant</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			@foreach($devices as $device)
			<tr>
				<td> {{ $device->name }}</td>
				<td> {{ $device->sigfox_id }}</td>
				<td> {{ $device->remote_id }}</td>
				<td> {{ $device->remote_name }}</td>
				<td>
					<form action="{{ url('/devices/'.$device->auth) }}">
						{{method_field('GET')}}
						{!! csrf_field() !!}
						<button class="btn btn-small btn-info mb-1 col-12" type="submit">Visualiser le device</button>
					</form>
				</td>
			</tr>
			@endforeach
		</tbody>
	</table>
	{{ $devices->links() }}
</div>
@endsection
@section('pagespecificscripts')
<script type="text/javascript" charset="utf-8">
	$('div.alert').not('.alert-important').delay(3000).fadeOut(350);
</script>
@endsection

resources/views/device/show.blade.php
@extends('layouts.main')

@section('content')
<div style="display: flex;">
	<div>
		<h1>Mes devices</h1>
	</div>
	<div id="main-button-container">
		<form class="main-button" action="{{ url('/devices/' . $device->auth . '/temperature') }}">
			{{method_field('GET')}}
			{!! csrf_field() !!}
			<button class="btn btn-small btn-secondary mb-1 col-12" type="submit">Suivre ma température</button>
		</form>
		<form class="main-button" action="{{ url('/devices/' . $device->auth . '/battery') }}">
			{{method_field('GET')}}
			{!! csrf_field() !!}
			<button class="btn btn-small btn-secondary mb-1 col-12" type="submit">Suivre ma batterie</button>
		</form>
	</div>
</div>
@include('flash::message')
<div class="jumbotron text-center">
	<h2></h2>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>Nom</th>
				<th>ID Sigfox</th>
				<th>ID distant</th>
				<th>Nom distant</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td> {{ $device->name }}</td>
				<td> {{ $device->sigfox_id }}</td>
				<td> {{ $device->remote_id }}</td>
				<td> {{ $device->remote_name }}</td>
				<td>
					<form action="{{ url('/devices/'.$device->auth.'/edit') }}" method="post">
						{{method_field('GET')}}
						{!! csrf_field() !!}
						<button class="btn btn-small btn-info mb-1 w-50" type="submit">Modifier le device</button>
					</form>
					<form action="{{ url('/devices', [$device->auth]) }}" method="post">
						{{method_field('DELETE')}}
						{!! csrf_field() !!}
						<button class="btn btn-small btn-outline-danger w-50" type="submit">Supprimer le device</button>
					</form>
				</td>
			</tr>
		</tbody>
	</table>
</div>
@endsection
@section('pagespecificscripts')
<script type="text/javascript" charset="utf-8">
	$('div.alert').not('.alert-important').delay(3000).fadeOut(350);
</script>
@endsection